import os
from datetime import datetime
from PSBOTS import run_psbots
from OOSPSBOTS import run_oospsbots

def run_combined_bot_process():
    date_time = str(datetime.now().date())
    bot_select = input("Input BotIDs:")
    bot_list = [int(num) for num in bot_select.split()]  # Process the list

    output_dir = f"C:/Users/cvickery/TRAVELER_PDFs{date_time}"
    os.makedirs(output_dir, exist_ok=True)

    psbots_generated_files, missing_bots = run_psbots(bot_list, output_dir)

    if psbots_generated_files is None:
        psbots_generated_files = []

    # Combine missing bots from PSBOTS and those with blank alarms
    all_missing_bots = [bot_id for bot_id in bot_list if bot_id not in psbots_generated_files] + missing_bots

    if all_missing_bots:
        print(f"Running OOSPSBOTS for missing bot IDs: {all_missing_bots}")
        run_oospsbots(all_missing_bots, output_dir)
    else:
        print("All files were generated by PSBOTS.")

if __name__ == "__main__":
    run_combined_bot_process()
