import os
from datetime import datetime
from PSBOTS import run_psbots
from OOSPSBOTS import run_oospsbots
import sys


def resource_path(relative_path):
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)


# Update your PDF template paths
template_alpha = resource_path("SymBot AlphaC Traveler v16.pdf")
template_symbot = resource_path("SymBot 1.0 Traveler vH.pdf")


def run_combined_bot_process():
    # Get current date for output directory
    date_time = str(datetime.now().date())

    # Input bot IDs
    bot_select = input("Input BotIDs (space-separated): ")
    bot_list = [int(num) for num in bot_select.split()]  # Process the list into integers

    # Define output directory
    output_dir = f"C:/Users/cvickery/TRAVELER_PDFs{date_time}"
    os.makedirs(output_dir, exist_ok=True)

    # Run PSBOTS process
    psbots_generated_files, missing_bots = run_psbots(bot_list, output_dir)

    # Debugging logs
    print("\nDEBUGGING INFO:")
    print(f"Input bot_list: {bot_list}")
    print(f"PSBOTS generated files: {psbots_generated_files}")
    print(f"Missing bots flagged by PSBOTS: {missing_bots}")

    # Handle NoneType for psbots_generated_files
    if psbots_generated_files is None:
        psbots_generated_files = []

    # Extract bot IDs from generated file paths
    generated_bot_ids = [
        int(os.path.basename(file).split('_')[2])  # Assuming filenames include bot IDs
        for file in psbots_generated_files
    ]

    # Debugging: Check extracted bot IDs
    print(f"Extracted bot IDs from PSBOTS files: {generated_bot_ids}")

    # Ensure no duplicates or incorrect bots in all_missing_bots
    all_missing_bots = list(set(bot_list) - set(generated_bot_ids) | set(missing_bots))

    # Additional debugging logs
    print(f"Final missing bots to process by OOSPSBOTS: {all_missing_bots}\n")

    # Run OOSPSBOTS if there are any missing bots
    if all_missing_bots:
        print(f"Running OOSPSBOTS for missing bot IDs: {all_missing_bots}")
        run_oospsbots(all_missing_bots, output_dir)
    else:
        print("All files were successfully generated by PSBOTS.")


if __name__ == "__main__":
    run_combined_bot_process()
